#!/usr/bin/fish
set DEVICE_NAME "AT Translated Set 2 keyboard"

function keyboard_state
    return (test (xinput list-props "$DEVICE_NAME" | grep "Device Enabled" | awk '{ print $4 }' | sed 's/[^0-9]*//g') -eq 1)
end

if test "$BLOCK_BUTTON" = "1"
    if keyboard_state
        xinput set-prop "$DEVICE_NAME" "Device Enabled" 0 # Disable
    else
        xinput set-prop "$DEVICE_NAME" "Device Enabled" 1 # Enable
    end
end

if keyboard_state
    echo "1"
else
    echo "0"
end
