#!/bin/bash
STRING="$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata' 2>/dev/null | awk '/artist/{getline; getline; print}' | cut -d'"' -f2) - $(dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata' 2>/dev/null | awk '/title/{getline; print}' | cut -d'"' -f2)"

if [ "$STRING" != " - " ]; then
  echo -n "<span foreground=\"#1DB954\">"
  echo -n  $STRING
  echo "</span>"
fi

if [ $BLOCK_BUTTON -eq 1 ]; then
  dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
fi

