#!/bin/bash
cat /proc/net/wireless | awk -v ssid=$(iwgetid -r) '/wlan0/ {
    level = int($4)
    color = (level >= -60) ? "00ff00" : (level >= -80) ? "ffff00" : "ff0000"
    print "<span foreground=\"#"color"\">WLAN: "level" dBm in "ssid"</span>"
    exit
}' | tr -d .
exit 0
