#!/bin/sh
pgrep -x "i3" > /dev/null || exit 0

# Debounce keys
sleep 0.4 

echo "Locking screen"

# Display options
xset dpms force off
xset dpms 0 0 10

# Locking
W="ffffff00"
B="00000000"

i3lock -n -t --indicator --indpos="x+w/2:y+h*703/1000" \
    -i "$HOME/Bilder/Wallpapers/Lockscreen.png" \
    --timecolor=$W --ringcolor="ffffffa0" --insidecolor=$B --linecolor=$W \
    --verifcolor=$W --ringvercolor="ffc107ff" --insidevercolor="ffc10748" \
    --wrongcolor=$W --ringwrongcolor="d32f2fff" --insidewrongcolor="d32d2f48" \
    --separatorcolor=$W --keyhlcolor="fffffffa"

echo "Screen unlocked"

# Display options
xset dpms 0 0 1800
# EOF
